[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"
  NEXT_PUBLIC_IRP_PROFILE_ENABLED = "true"
  NEXT_PUBLIC_EPP_PROFILE_ENABLED = "true"
  NEXT_PUBLIC_SPACES_ENABLED = "true"
  NEXT_PUBLIC_WORKSPACE_ASSET_RAIL_V2 = "true"

