/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Otp */
        post: operations["request_otp_api_v1_auth_otp_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Otp */
        post: operations["verify_otp_api_v1_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/webapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Telegram Miniapp
         * @description Validate Telegram Mini App initData and issue a JWT (same shape as OTP verify).
         */
        post: operations["auth_telegram_miniapp_api_v1_auth_telegram_webapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram-miniapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Telegram Miniapp
         * @description Validate Telegram Mini App initData and issue a JWT (same shape as OTP verify).
         */
        post: operations["auth_telegram_miniapp_api_v1_auth_telegram_miniapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        /** Patch Me */
        put: operations["patch_me_api_v1_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/bind/phone/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind Phone Request */
        post: operations["bind_phone_request_api_v1_me_bind_phone_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/bind/phone/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind Phone Confirm */
        post: operations["bind_phone_confirm_api_v1_me_bind_phone_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cv/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cv Documents List */
        get: operations["cv_documents_list_api_v1_cv_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cv/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cv Document Detail */
        get: operations["cv_document_detail_api_v1_cv_documents__doc_id__get"];
        /** Cv Document Edit */
        put: operations["cv_document_edit_api_v1_cv_documents__doc_id__put"];
        post?: never;
        /** Cv Document Delete */
        delete: operations["cv_document_delete_api_v1_cv_documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cv/documents/{doc_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cv Export Pdf */
        post: operations["cv_export_pdf_api_v1_cv_documents__doc_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interview/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Interview Session
         * @description Create a new interview session and return the first question.
         *     Does NOT charge the user at this point (per business rule §14.1).
         */
        post: operations["create_interview_session_api_v1_interview_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interview/sessions/{session_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Answer
         * @description Submit an answer to the current question.
         *     - First valid answer triggers credit/entitlement consumption (§14.1).
         *     - Returns next question or completion signal.
         */
        post: operations["submit_answer_api_v1_interview_sessions__session_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interview/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interview Session
         * @description Get interview session details / feedback report.
         *     Returns feedback_pending if still generating, or full feedback if ready.
         */
        get: operations["get_interview_session_api_v1_interview_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interview/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interview History
         * @description Return all interview sessions for the current user, newest first.
         *     Includes completed, abandoned, feedback_pending, and feedback_failed.
         */
        get: operations["get_interview_history_api_v1_interview_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-tasks/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Today Task
         * @description GET /api/v1/daily-tasks/today
         *     Returns the current user's daily task for today (UTC+5).
         *     If no task exists yet, creates one based on user profile.
         *     Lazily expires stale tasks from previous days.
         */
        get: operations["get_today_task_api_v1_daily_tasks_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-tasks/today/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Respond To Task
         * @description POST /api/v1/daily-tasks/today/respond
         *     Submit a response to today's daily task.
         *     Marks task as completed, updates streak, triggers AI feedback in background.
         */
        post: operations["respond_to_task_api_v1_daily_tasks_today_respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-tasks/today/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Task
         * @description POST /api/v1/daily-tasks/today/skip
         *     Skip today's daily task. No new task will be issued today.
         *     Per business rules §21.13: skipped tasks are not re-issued on the same day.
         */
        post: operations["skip_task_api_v1_daily_tasks_today_skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Plan
         * @description GET /api/v1/plans/current
         *     Reserved interface (Phase 2). Returns a placeholder plan summary.
         *     Per API Spec v2.5 §6.5: this endpoint is reserved and returns a locked plan
         *     until the full sprint plan feature is implemented in Phase 2.
         */
        get: operations["get_current_plan_api_v1_plans_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Billing Summary
         * @description 返回当前用户的 Credits 余额（含分桶）和有效权益列表。
         *     API Spec v2.5 §7.1
         */
        get: operations["get_billing_summary_api_v1_billing_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Order
         * @description 创建 Kaspi 订单，返回静态 QR 占位图和 reference_code。
         *     API Spec v2.5 §7.2
         */
        post: operations["create_order_api_v1_billing_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Order Status
         * @description 查询订单状态。
         *     - pending/pending → 200
         *     - paid/retry_pending → 202
         *     - paid/fulfilled → 200（含 credits_added, new_balance）
         *     - 不存在或跨用户 → 404
         *     API Spec v2.5 §7.3
         */
        get: operations["get_order_status_api_v1_billing_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/orders/{order_id}/mock-fulfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mock Fulfill Order
         * @description Simulate Kaspi payment fulfillment when real Kaspi account is unavailable.
         *     Requires ALLOW_MOCK_FULFILL=true in environment.
         */
        post: operations["mock_fulfill_order_api_v1_billing_orders__order_id__mock_fulfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Input
         * @description 统一文本/语音输入：ASR 转写 + canonical_text 清洗 + user_inputs 落库。
         *     Content-Type: multipart/form-data
         */
        post: operations["create_input_api_v1_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/next-best-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Next Best Action */
        get: operations["get_user_next_best_action_api_v1_users__user_id__next_best_action_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Recommendations */
        get: operations["list_job_recommendations_api_v1_job_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Detail */
        get: operations["get_job_detail_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Agent */
        get: operations["get_active_agent_api_v1_agents_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Agent */
        post: operations["activate_agent_api_v1_agents__agent_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Agent */
        post: operations["deactivate_agent_api_v1_agents__agent_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agent Chat
         * @description Agent Hub chat. Language: Full resolution order (KAZI-74): (1) X-Language-Preference header; (2) body language_preference; (3) body locale; (4) X-Locale legacy header; (5) authenticated Profile language_preference (GET /me); (6) phone-country inference only when Profile unset; (7) default ru. Accept-Language is NOT supported — use X-Language-Preference or Profile SSOT.
         */
        post: operations["agent_chat_api_v1_agents_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Messages */
        get: operations["get_session_messages_api_v1_agents_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Init Telegram Login
         * @description Step 1 of deep-link login flow.
         *     Frontend calls this to get a one-time token, then redirects user to:
         *     https://t.me/KaziSpaceBot?start=login_<token>
         *     API Spec v2.3 §2.3: no request body required (anonymous-friendly).
         */
        post: operations["init_telegram_login_api_v1_auth_telegram_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/poll/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll Telegram Login
         * @description Step 3: Frontend polls this endpoint until login is confirmed.
         *     Returns {status: 'pending'} or {status: 'ok', access_token, user: {...}}
         *     API Spec v2.3 §2.3: 成功时必须返回 JWT access_token，便于前端后续认证请求。
         */
        get: operations["poll_telegram_login_api_v1_auth_telegram_poll__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Telegram
         * @description Verify Telegram Login Widget callback and bind Telegram identity
         *     to the unified user account.
         *
         *     Flow:
         *     1. Verify HMAC signature from Telegram
         *     2. Look up existing Telegram identity in user_identities
         *     3. If web_user_id provided, try to merge with existing web user
         *     4. Create or update user record
         *     5. Return unified user_id + credits balance
         */
        post: operations["auth_telegram_api_v1_auth_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bind User
         * @description Web 端：绑定或创建用户，返回 user_id 和当前 credits 余额
         */
        post: operations["bind_user_api_v1_user_bind_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Web Chat
         * @description Web Chat (API Spec v2.3 §3.3). Language: Full resolution order (KAZI-74): (1) X-Language-Preference header; (2) body language_preference; (3) body locale; (4) X-Locale legacy header; (5) authenticated Profile language_preference (GET /me); (6) phone-country inference only when Profile unset; (7) default ru. Accept-Language is NOT supported — use X-Language-Preference or Profile SSOT.
         */
        post: operations["web_chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Web Chat
         * @description Web Chat (API Spec v2.3 §3.3). Language: Full resolution order (KAZI-74): (1) X-Language-Preference header; (2) body language_preference; (3) body locale; (4) X-Locale legacy header; (5) authenticated Profile language_preference (GET /me); (6) phone-country inference only when Profile unset; (7) default ru. Accept-Language is NOT supported — use X-Language-Preference or Profile SSOT.
         */
        post: operations["web_chat_api_v1_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/history/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat History */
        get: operations["get_chat_history_api_v1_chat_history__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat History */
        get: operations["get_chat_history_api_v1_chat_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Spaces
         * @description List spaces. Lazily bootstraps Clinic on first access (writes + commit).
         *
         *     P1 follow-up: move bootstrap to login/`GET /me` so this endpoint stays read-only.
         *     Concurrent bootstrap is safe via `uq_spaces_user_clinic` + IntegrityError retry in store.
         */
        get: operations["list_spaces_api_v1_spaces_get"];
        put?: never;
        /** Post Create Space */
        post: operations["post_create_space_api_v1_spaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{space_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Space */
        get: operations["get_space_api_v1_spaces__space_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{space_id}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Space Turn
         * @description Space turn — unified user message path (ADR-006 §1.5). P0.5 returns envelope stub.
         */
        post: operations["post_space_turn_api_v1_spaces__space_id__turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/space-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_space_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivateRequest */
        ActivateRequest: {
            /** Handoff Message */
            handoff_message?: string | null;
            /**
             * Referral Reason
             * @default user_selected
             */
            referral_reason: string;
        };
        /** AgentChatRequest */
        AgentChatRequest: {
            /** Agent Id */
            agent_id: string;
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
            /** Request Id */
            request_id?: string | null;
        };
        /** BindPhoneConfirmBody */
        BindPhoneConfirmBody: {
            /** Phone */
            phone: string;
            /** Code */
            code: string;
            /** Otp Request Id */
            otp_request_id?: number | string | null;
        };
        /** BindPhoneRequestBody */
        BindPhoneRequestBody: {
            /** Phone */
            phone: string;
        };
        /** Body_create_input_api_v1_inputs_post */
        Body_create_input_api_v1_inputs_post: {
            /** Source Channel */
            source_channel: string;
            /** Input Mode */
            input_mode: string;
            /** Text */
            text?: string | null;
            /** Device Id */
            device_id?: string | null;
            /** Context Module */
            context_module?: string | null;
            /** File */
            file?: string | null;
        };
        /**
         * CreateInputResponse
         * @description POST /api/v1/inputs response (text or voice). Voice: FE sends chat only when asr_fallback_triggered is false and canonical_text is non-empty (KAZI-214).
         */
        CreateInputResponse: {
            /** Input Id */
            input_id: number;
            /** Input Mode */
            input_mode: string;
            /** Canonical Text */
            canonical_text: string;
            /** Transcription Confidence */
            transcription_confidence?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Asr Fallback Triggered
             * @description When true, FE must not send chat; prompt user to re-record or type.
             */
            asr_fallback_triggered?: boolean;
        };
        /** CreateOrderRequest */
        CreateOrderRequest: {
            /** Package Id */
            package_id: string;
            /** Amount Kzt */
            amount_kzt: number;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Target Role */
            target_role: string;
            /** Interview Level */
            interview_level: string;
            /**
             * Answer Mode
             * @default text
             */
            answer_mode: string;
            /**
             * Source Channel
             * @default web
             */
            source_channel: string;
            /** Job Id */
            job_id?: string | null;
        };
        /** CvEditRequest */
        CvEditRequest: {
            /** Mode */
            mode: string;
            /** Content Markdown */
            content_markdown?: string | null;
            /** Instruction */
            instruction?: string | null;
        };
        /** DeactivateRequest */
        DeactivateRequest: {
            /**
             * Reason
             * @default user_requested
             */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OtpRequestBody */
        OtpRequestBody: {
            /** Phone */
            phone: string;
        };
        /** OtpVerifyBody */
        OtpVerifyBody: {
            /** Phone */
            phone: string;
            /** Otp Code */
            otp_code?: string | null;
            /** Code */
            code?: string | null;
            /** Otp Request Id */
            otp_request_id?: number | string | null;
        };
        /**
         * PatchMeBody
         * @description Partial profile update — all fields optional. Language: send language_preference (preferred) or primary_locale; if both sent, language_preference wins. Omit a field to leave unchanged; null is treated as omit (no clear-to-null in MVP).
         */
        PatchMeBody: {
            /** Primary Country */
            primary_country?: string | null;
            /**
             * Primary Locale
             * @description Transition alias for language_preference. Optional on PATCH. Valid enum updates Profile SSOT. Clearing not supported in MVP — unset users fall back to phone inference then default ru.
             */
            primary_locale?: components["schemas"]["NullableLanguageCode"];
            /**
             * Language Preference
             * @description Formal name (KAZI-74). Maps to primary_locale DB column in MVP. Optional on PATCH. Valid enum updates Profile SSOT. Clearing not supported in MVP — unset users fall back to phone inference then default ru.
             */
            language_preference?: components["schemas"]["NullableLanguageCode"];
            /** Career Goal */
            career_goal?: string | null;
            /** Target Role */
            target_role?: string | null;
            /** English Level */
            english_level?: string | null;
            /** Weekly Hours Budget */
            weekly_hours_budget?: number | null;
            /** Current Status */
            current_status?: string | null;
            /** Education Text */
            education_text?: string | null;
            /** Experience Text */
            experience_text?: string | null;
        };
        /** RespondRequest */
        RespondRequest: {
            /** Task Id */
            task_id: string;
            /** Response Text */
            response_text: string;
        };
        /** SkipRequest */
        SkipRequest: {
            /** Task Id */
            task_id: string;
            /**
             * Reason
             * @default other
             */
            reason: string | null;
        };
        /** SubmitAnswerRequest */
        SubmitAnswerRequest: {
            /** Question Id */
            question_id: string;
            /** Answer Text */
            answer_text: string;
        };
        /** TelegramAuthRequest */
        TelegramAuthRequest: {
            /** Id */
            id: number;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Username */
            username?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Auth Date */
            auth_date: number;
            /** Hash */
            hash: string;
            /** Web User Id */
            web_user_id?: string | null;
        };
        /** TelegramMiniAppAuthBody */
        TelegramMiniAppAuthBody: {
            /** Init Data */
            init_data: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebChatRequest */
        WebChatRequest: {
            /** Session Id */
            session_id?: string | null;
            /** Content */
            content?: string | null;
            /**
             * Locale
             * @description Transition alias for per-turn language (KAZI-74). If both locale and language_preference are sent in the body, language_preference wins. Request headers outrank body fields.
             */
            locale?: components["schemas"]["NullableLanguageCode"];
            /**
             * Language Preference
             * @description Per-turn UI/chat language hint (KAZI-74 formal name). See X-Language-Preference header for full resolution order.
             */
            language_preference?: components["schemas"]["NullableLanguageCode"];
            /** Web User Id */
            web_user_id?: string | null;
            /** Message */
            message?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Activate Agent */
            activate_agent?: string | null;
            /** Exit Agent */
            exit_agent?: boolean | null;
        };
        /** WebUserBindRequest */
        WebUserBindRequest: {
            /** Web User Id */
            web_user_id: string;
            /** Telegram Id */
            telegram_id?: string | null;
            /** Whatsapp Phone */
            whatsapp_phone?: string | null;
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name?: string | null;
        };
        /** ActiveEntitlementBlock */
        ActiveEntitlementBlock: {
            /** Type */
            type: string;
            /** Expire At */
            expire_at?: string | null;
        };
        /** BillingSnapshotBlock */
        BillingSnapshotBlock: {
            /** Credits */
            credits: number;
            active_entitlement?: components["schemas"]["ActiveEntitlementBlock"] | null;
            /** Is Paid */
            is_paid: boolean;
        };
        /** CapabilitiesBlock */
        CapabilitiesBlock: {
            /** Can Save Progress */
            can_save_progress: boolean;
            /** Can View Full Plan */
            can_view_full_plan: boolean;
            /** Can Access Web App */
            can_access_web_app: boolean;
            /** Can Purchase */
            can_purchase: boolean;
            /** Can Use Paid Features */
            can_use_paid_features: boolean;
        };
        /** CreateInterviewSessionResponse */
        CreateInterviewSessionResponse: {
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @constant
             */
            status: "in_progress";
            /** Interview Level */
            interview_level: string;
            /** Charged */
            charged: boolean;
            /** Question Index */
            question_index: number;
            /** Question Count */
            question_count: number;
            /** Estimated Duration Minutes */
            estimated_duration_minutes: number;
            /** Language Notice */
            language_notice: string;
            question: components["schemas"]["InterviewQuestionBlock"];
            prep_card?: components["schemas"]["InterviewPrepCard"] | null;
            /**
             * Job Id
             * @description Echoed when sent; prep_card generation is KAZI-32 (schema ahead of runtime).
             */
            job_id?: string | null;
        };
        /**
         * InterviewPrepCard
         * @description Planned v0.2d depth (KAZI-32) — returned when ``job_id`` is set.
         */
        InterviewPrepCard: {
            /** Focus Areas */
            focus_areas?: string[];
            /** Sample Questions */
            sample_questions?: string[];
            /** Estimated Duration Min */
            estimated_duration_min?: number | null;
        };
        /** InterviewQuestionBlock */
        InterviewQuestionBlock: {
            /** Question Id */
            question_id: string;
            /** Category */
            category: string;
            /** Content */
            content: string;
        };
        /** JobDetailResponse */
        JobDetailResponse: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Logo Url */
            logo_url?: string | null;
            /** Location */
            location?: string | null;
            /** Work Mode */
            work_mode?: string | null;
            /** Salary */
            salary?: string | null;
            /** Description Text */
            description_text?: string | null;
            /** Required Skills */
            required_skills?: string[];
            /** Match Score */
            match_score: number;
            match_analysis: components["schemas"]["MatchAnalysisBlock"];
            /** Why Matched */
            why_matched?: string[];
            /** Gap To Close */
            gap_to_close?: string[];
            /** Apply Url */
            apply_url?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Source */
            source?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Primary Cta */
            primary_cta: string;
            /** Is Pro User */
            is_pro_user: boolean;
            /**
             * Pro Features Locked
             * @default false
             */
            pro_features_locked: boolean;
        };
        /** JobRecommendationItem */
        JobRecommendationItem: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Logo Url */
            logo_url?: string | null;
            /** Location */
            location?: string | null;
            /** Work Mode */
            work_mode?: string | null;
            /** Salary */
            salary?: string | null;
            /** Match Score */
            match_score: number;
            /** Match Level */
            match_level: string;
            /** Why Matched */
            why_matched?: string[];
            /** Gap To Close */
            gap_to_close?: string[];
            /** Ranking Reason */
            ranking_reason?: string | null;
            /** Primary Cta */
            primary_cta: string;
            /**
             * Is Saved
             * @default false
             */
            is_saved: boolean;
            /**
             * Is Locked
             * @default false
             */
            is_locked: boolean;
            /** Source */
            source?: string | null;
            /** Published At */
            published_at?: string | null;
        };
        /** JobRecommendationsResponse */
        JobRecommendationsResponse: {
            /** Items */
            items: components["schemas"]["JobRecommendationItem"][];
            /** Is Pro User */
            is_pro_user: boolean;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Generated At */
            generated_at: string;
            /** Total */
            total?: number | null;
            /** Engine Total */
            engine_total?: number | null;
            /** Upgrade Hint */
            upgrade_hint?: string | null;
        };
        /** MatchAnalysisBlock */
        MatchAnalysisBlock: {
            /** Overall Reason */
            overall_reason: string;
            scores: components["schemas"]["MatchAnalysisScores"];
            /** Why Matched */
            why_matched?: string[];
            /** Gap To Close */
            gap_to_close?: string[];
        };
        /** MatchAnalysisScores */
        MatchAnalysisScores: {
            /** Skills Match */
            skills_match: number;
            /** Experience Match */
            experience_match: number;
            /** Language Match */
            language_match: number;
            /** Preference Match */
            preference_match: number;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Status */
            status: string;
            /** Is Bound */
            is_bound: boolean;
            /** Is Paid */
            is_paid: boolean;
            /**
             * Primary Locale
             * @description Transition alias for language_preference (KAZI-74). Same value as language_preference when set. Null when Profile language not yet set.
             */
            primary_locale: components["schemas"]["NullableLanguageCode"];
            /**
             * Language Preference
             * @description User UI/chat/agent language (Profile SSOT). DB column still primary_locale in MVP.
             */
            language_preference: components["schemas"]["NullableLanguageCode"];
            /** Primary Country */
            primary_country?: string | null;
            /** Source Channel */
            source_channel?: string | null;
            /** Onboarding Stage */
            onboarding_stage?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** First Value At */
            first_value_at?: string | null;
            /** First Paid At */
            first_paid_at?: string | null;
            /** Hook State */
            hook_state: string;
            /** Hook State Label */
            hook_state_label: string;
            /** Hook State Updated At */
            hook_state_updated_at?: string | null;
            profile_completion: components["schemas"]["ProfileCompletionBlock"];
            profile?: components["schemas"]["UserProfileBlock"] | null;
            capabilities: components["schemas"]["CapabilitiesBlock"];
            billing_snapshot: components["schemas"]["BillingSnapshotBlock"];
        };
        /** ProfileCompletionBlock */
        ProfileCompletionBlock: {
            /** Minimum Fields Completed */
            minimum_fields_completed: number;
            /** Minimum Fields Total */
            minimum_fields_total: number;
            /** Minimum Complete */
            minimum_complete: boolean;
            /** Deferred Fields Completed */
            deferred_fields_completed: number;
            /** Deferred Fields Total */
            deferred_fields_total: number;
            /** Overall Pct */
            overall_pct: number;
            /** Missing Minimum */
            missing_minimum: string[];
        };
        /** UserProfileBlock */
        UserProfileBlock: {
            /** Career Goal */
            career_goal?: string | null;
            /** Target Role */
            target_role?: string | null;
            /** English Level */
            english_level?: string | null;
            /** Current Status */
            current_status?: string | null;
            /** Weekly Hours Budget */
            weekly_hours_budget?: number | null;
            /** Education Text */
            education_text?: string | null;
            /** Experience Text */
            experience_text?: string | null;
        };
        /**
         * Language Code
         * @description Supported UI/chat language (KAZI-74). Add new languages here only; reference via $ref elsewhere.
         * @enum {string}
         */
        LanguageCode: "en" | "ru" | "kk" | "uz" | "zh";
        /** Nullable Language Code */
        NullableLanguageCode: components["schemas"]["LanguageCode"] | null;
        /** CreateSpaceRequest */
        CreateSpaceRequest: {
            /**
             * Template Id
             * @description blank_conversation | job_sprint | ielts_prep
             */
            template_id: string;
            /** Name */
            name?: string | null;
        };
        /** CreateSpaceResponse */
        CreateSpaceResponse: {
            space: components["schemas"]["SpaceDetail"];
            /**
             * Master Session Id
             * @description Convenience duplicate of space.master_session_id for post-create navigation (design SDD §1.4); BE guarantees equality on create.
             */
            master_session_id: string;
        };
        /** SpaceDetail */
        SpaceDetail: {
            /**
             * Id
             * @description sp_* or __clinic__
             */
            id: string;
            /** Name */
            name: string;
            /** Template Id */
            template_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "archived" | "deleted";
            /**
             * Is Entry Point
             * @default false
             */
            is_entry_point: boolean;
            /**
             * Is System
             * @default false
             */
            is_system: boolean;
            /** Last Active At */
            last_active_at?: string | null;
            /** Template Icon */
            template_icon?: string | null;
            /** Template Display Name */
            template_display_name?: string | null;
            /** Master Session Id */
            master_session_id: string;
            /** Config Snapshot */
            config_snapshot?: {
                [key: string]: unknown;
            };
            /** Space State */
            space_state?: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** SpaceListResponse */
        SpaceListResponse: {
            /** Spaces */
            spaces?: components["schemas"]["SpaceSummary"][];
        };
        /**
         * SpaceSummary
         * @description Sidebar row — ``GET /api/v1/spaces`` item (design SDD §1.4).
         */
        SpaceSummary: {
            /**
             * Id
             * @description sp_* or __clinic__
             */
            id: string;
            /** Name */
            name: string;
            /** Template Id */
            template_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "archived" | "deleted";
            /**
             * Is Entry Point
             * @default false
             */
            is_entry_point: boolean;
            /**
             * Is System
             * @default false
             */
            is_system: boolean;
            /** Last Active At */
            last_active_at?: string | null;
            /** Template Icon */
            template_icon?: string | null;
            /** Template Display Name */
            template_display_name?: string | null;
        };
        /** SpaceTemplateItem */
        SpaceTemplateItem: {
            /** Template Id */
            template_id: string;
            /** Display Name */
            display_name?: {
                [key: string]: string;
            };
            /**
             * Mvp
             * @default false
             */
            mvp: boolean;
        };
        /** SpaceTemplatesResponse */
        SpaceTemplatesResponse: {
            /** Templates */
            templates?: components["schemas"]["SpaceTemplateItem"][];
            /** Coming Soon */
            coming_soon?: components["schemas"]["SpaceTemplateItem"][];
        };
        /** SpaceTurnEnvelope */
        SpaceTurnEnvelope: {
            /** Components */
            components?: components["schemas"]["SpaceTurnEnvelopeComponent"][];
            meta: components["schemas"]["SpaceTurnEnvelopeMeta"];
        };
        /**
         * SpaceTurnEnvelopeComponent
         * @description Chat envelope component. ``text`` is populated when ``type`` is ``text``.
         */
        SpaceTurnEnvelopeComponent: {
            /** Type */
            type: string;
            /** Text */
            text?: string | null;
        };
        /**
         * SpaceTurnEnvelopeMeta
         * @description P0.5 core meta fields. Use ``extensions`` for forward-compatible keys (P2+).
         */
        SpaceTurnEnvelopeMeta: {
            /** Space Id */
            space_id: string;
            /** Engine */
            engine?: string | null;
            /** Mode */
            mode?: string | null;
            /** Template Id */
            template_id?: string | null;
            /** Echo Len */
            echo_len?: number | null;
            /**
             * Extensions
             * @description Additional meta from orchestrator; TODO(P2): tighten per-envelope-type schemas.
             */
            extensions?: {
                [key: string]: unknown;
            };
        };
        /** SpaceTurnRequest */
        SpaceTurnRequest: {
            /** Message */
            message: string;
            /** Input Mode */
            input_mode?: string | null;
            /** Attachments */
            attachments?: components["schemas"]["SpaceTurnAttachment"][] | null;
        };
        /** SpaceTurnResponse */
        SpaceTurnResponse: {
            envelope: components["schemas"]["SpaceTurnEnvelope"];
        };
        /**
         * SpaceTurnAttachment
         * @description File attachment on a space turn request.
         */
        SpaceTurnAttachment: {
            /** Id */
            id?: string | null;
            /** Type */
            type?: string | null;
            /** Name */
            name?: string | null;
            /** Size */
            size?: number | null;
            /** Mime Type */
            mime_type?: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: {
        /** @description Explicit UI/chat language for this request (KAZI-74). Full resolution order (KAZI-74): (1) X-Language-Preference header; (2) body language_preference; (3) body locale; (4) X-Locale legacy header; (5) authenticated Profile language_preference (GET /me); (6) phone-country inference only when Profile unset; (7) default ru. Accept-Language is NOT supported — use X-Language-Preference or Profile SSOT. */
        "X-Language-Preference": components["schemas"]["LanguageCode"];
        /** @description Legacy header for pre-KAZI-74 clients (mirrors next-intl URL route segment). When both X-Language-Preference and X-Locale are present, X-Language-Preference wins. Will be deprecated after client migration; do not use as the sole language signal. */
        "X-Locale": components["schemas"]["LanguageCode"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_otp_api_v1_auth_otp_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_api_v1_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_telegram_miniapp_api_v1_auth_telegram_webapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramMiniAppAuthBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_telegram_miniapp_api_v1_auth_telegram_miniapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramMiniAppAuthBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    patch_me_api_v1_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_phone_request_api_v1_me_bind_phone_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindPhoneRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_phone_confirm_api_v1_me_bind_phone_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindPhoneConfirmBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cv_documents_list_api_v1_cv_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cv_document_detail_api_v1_cv_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cv_document_edit_api_v1_cv_documents__doc_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CvEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cv_document_delete_api_v1_cv_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cv_export_pdf_api_v1_cv_documents__doc_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interview_session_api_v1_interview_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInterviewSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_v1_interview_sessions__session_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_session_api_v1_interview_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_history_api_v1_interview_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_today_task_api_v1_daily_tasks_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    respond_to_task_api_v1_daily_tasks_today_respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespondRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_task_api_v1_daily_tasks_today_skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_plan_api_v1_plans_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_billing_summary_api_v1_billing_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_order_api_v1_billing_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_status_api_v1_billing_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mock_fulfill_order_api_v1_billing_orders__order_id__mock_fulfill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_input_api_v1_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_input_api_v1_inputs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_next_best_action_api_v1_users__user_id__next_best_action_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_recommendations_api_v1_job_recommendations_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_detail_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_active_agent_api_v1_agents_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    activate_agent_api_v1_agents__agent_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_agent_api_v1_agents__agent_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeactivateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_chat_api_v1_agents_chat_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Explicit UI/chat language for this request (KAZI-74). Full resolution order (KAZI-74): (1) X-Language-Preference header; (2) body language_preference; (3) body locale; (4) X-Locale legacy header; (5) authenticated Profile language_preference (GET /me); (6) phone-country inference only when Profile unset; (7) default ru. Accept-Language is NOT supported — use X-Language-Preference or Profile SSOT. */
                "X-Language-Preference"?: components["parameters"]["X-Language-Preference"];
                /** @description Legacy header for pre-KAZI-74 clients (mirrors next-intl URL route segment). When both X-Language-Preference and X-Locale are present, X-Language-Preference wins. Will be deprecated after client migration; do not use as the sole language signal. */
                "X-Locale"?: components["parameters"]["X-Locale"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_messages_api_v1_agents_sessions__session_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    init_telegram_login_api_v1_auth_telegram_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    poll_telegram_login_api_v1_auth_telegram_poll__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_telegram_api_v1_auth_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_user_api_v1_user_bind_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebUserBindRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    web_chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Explicit UI/chat language for this request (KAZI-74). Full resolution order (KAZI-74): (1) X-Language-Preference header; (2) body language_preference; (3) body locale; (4) X-Locale legacy header; (5) authenticated Profile language_preference (GET /me); (6) phone-country inference only when Profile unset; (7) default ru. Accept-Language is NOT supported — use X-Language-Preference or Profile SSOT. */
                "X-Language-Preference"?: components["parameters"]["X-Language-Preference"];
                /** @description Legacy header for pre-KAZI-74 clients (mirrors next-intl URL route segment). When both X-Language-Preference and X-Locale are present, X-Language-Preference wins. Will be deprecated after client migration; do not use as the sole language signal. */
                "X-Locale"?: components["parameters"]["X-Locale"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    web_chat_api_v1_chat_messages_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Explicit UI/chat language for this request (KAZI-74). Full resolution order (KAZI-74): (1) X-Language-Preference header; (2) body language_preference; (3) body locale; (4) X-Locale legacy header; (5) authenticated Profile language_preference (GET /me); (6) phone-country inference only when Profile unset; (7) default ru. Accept-Language is NOT supported — use X-Language-Preference or Profile SSOT. */
                "X-Language-Preference"?: components["parameters"]["X-Language-Preference"];
                /** @description Legacy header for pre-KAZI-74 clients (mirrors next-intl URL route segment). When both X-Language-Preference and X-Locale are present, X-Language-Preference wins. Will be deprecated after client migration; do not use as the sole language signal. */
                "X-Locale"?: components["parameters"]["X-Locale"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_history_api_v1_chat_history__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_history_api_v1_chat_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_spaces_api_v1_spaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceListResponse"];
                };
            };
        };
    };
    post_create_space_api_v1_spaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSpaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_space_api_v1_spaces__space_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_space_turn_api_v1_spaces__space_id__turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_space_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceTemplatesResponse"];
                };
            };
        };
    };
}
